// SPDX-License-Identifier: GPL-2.0
/*
 * Debug plumbing, and a partial recovery of the module parameters.
 *
 * The blob's own __param section had to be dropped (2.6.36 layout - see
 * TODO.md), so none of its tunables can be set on the insmod line any more.
 * But *our* module_param() calls are generated by kbuild in the correct 6.12
 * layout, so we can hand back the ones that matter by writing the blob's
 * globals before its init runs.
 *
 * wl_msg_level is the important one during bring-up: the driver's WL_ERROR()
 * and friends are gated on it, and it is how you find out why an attach
 * failed instead of guessing at an error number.
 *
 * Bit values are from vendor/include/wlioctl.h:
 *   0x00000001  WL_ERROR_VAL
 *   0x00000002  WL_TRACE_VAL
 *   0x00000010  WL_INFORM_VAL
 */

#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/moduleparam.h>
#include <linux/string.h>

#include "wl_shadow.h"

/*
 * The blob's interface-name template, a char[IFNAMSIZ] in its .data. Empty by
 * default, in which case the driver falls back to "eth%d" and the interface
 * comes up as ethN rather than wl0. This was one of the eight tunables lost
 * when the blob's 2.6.36 __param section had to be dropped; handing it back
 * this way is the pattern described in TODO.md, and the same one-liner works
 * for any other blob global worth exposing.
 *
 * It is a *local* symbol in the blob (module_param_string made it static), so
 * the Makefile also passes --globalize-symbol intf_name to make it reachable
 * from here. Same trick applies to nompc and instance_base if they are ever
 * wanted.
 */
extern char intf_name[16];

/* Defined by the blob. */
extern uint wl_msg_level;
extern uint wl_msg_level2;
extern uint phyhal_msg_level;

/*
 * Broadcom builds its NVRAM variable prefix as "pci/<bus>/<slot>/", where
 * <bus> is osl_pci_bus() == the PCI *domain* on ARMv7. FreshTomato's Northstar
 * PCIe driver numbered domains from 1; mainline's PCIE_IPROC_BCMA numbers them
 * from 0. So the R7000's radios sit at domain 0 and 1 here, while its NVRAM
 * holds pci/1/1/... and pci/2/1/... - off by one, and every per-radio variable
 * (macaddr, sromrev, boardflags, ccode) goes unfound.
 *
 * A parameter rather than a constant because each test costs a reboot: if the
 * numbering differs on another board, try 0 or 2 without rebuilding.
 */
int wl_pci_domain_offset = 1;
module_param_named(pcidomain_offset, wl_pci_domain_offset, int, 0644);
MODULE_PARM_DESC(pcidomain_offset,
		 "added to the PCI domain when building the NVRAM devpath (default 1)");

static char ifname[16];
module_param_string(intf_name, ifname, sizeof(ifname), 0);
MODULE_PARM_DESC(intf_name,
		 "interface name template, e.g. wl%d; empty means the driver's eth%d");

static uint msglevel = 0x0001;		/* WL_ERROR_VAL */
static uint msglevel2;
static uint phymsglevel;

module_param(msglevel, uint, 0644);
MODULE_PARM_DESC(msglevel, "wl_msg_level: 1=errors, 2=trace, 0x10=inform");
module_param(msglevel2, uint, 0644);
MODULE_PARM_DESC(msglevel2, "wl_msg_level2");
module_param(phymsglevel, uint, 0644);
MODULE_PARM_DESC(phymsglevel, "phyhal_msg_level");

void wl_shadow_debug_init(void)
{
	if (ifname[0])
		strscpy(intf_name, ifname, sizeof(intf_name));

	wl_msg_level     = msglevel;
	wl_msg_level2    = msglevel2;
	phyhal_msg_level = phymsglevel;

	/*
	 * dma_trace is echoed here on purpose. A trace run that produces no
	 * output is ambiguous - "the function is never called" and "the
	 * parameter was not passed" look identical in dmesg - and that
	 * ambiguity cost a whole hardware cycle. Now the log always says which.
	 */
	pr_info("wl: msg levels set (wl=0x%x wl2=0x%x phy=0x%x), intf_name='%s', "
		"dma_trace=%d\n",
		wl_msg_level, wl_msg_level2, phyhal_msg_level,
		intf_name[0] ? intf_name : "(default eth%d)", wl_dma_trace);
}

/*
 * TX-ring tracing, off by default.
 *
 * It was defaulted on while the transmit-status desynchronisation was being
 * chased, because a trace that depends on remembering a flag is a trace that
 * does not happen - two hardware cycles were lost exactly that way. That fault
 * is fixed now, so the default goes back to silent, but the switch stays: it
 * found the bug and the receive path has had far less scrutiny than transmit.
 *
 * `insmod wl.ko dma_trace=400` logs 400 ring events - one line per
 * dma64_txfast() enqueue and dma64_getnexttxp() reclaim, with the ring indices,
 * the packet, and the TxFrameID as the driver wrote it. Compare that last
 * against the pair wlc_dotxstatus() complains about; see TESTING.md.
 *
 * The value is echoed in the init line on purpose. "The code never ran" and
 * "the parameter was not set" look identical in dmesg otherwise.
 */
int wl_dma_trace;
module_param_named(dma_trace, wl_dma_trace, int, 0644);
MODULE_PARM_DESC(dma_trace, "number of DMA tx enqueue/complete events to log (0 = off)");

/*
 * Receive tracing, off by default.
 *
 * `insmod wl.ko rx_trace=60` dumps 60 received frames as netif_rx() sees them,
 * from the mac header - which is what the bridge reads to learn a source
 * address, and how the ->cloned bug was caught: group-addressed frames were
 * arriving with an intact LLC/SNAP header where the source MAC belonged.
 *
 * Built with WL_SKB_OPS_TRACE=1 each frame is preceded by the push/pull moves
 * that produced it. That is compile-time because the ring costs memory per
 * packet; see wl_shadow_skb.h.
 */
int wl_rx_trace;
module_param_named(rx_trace, wl_rx_trace, int, 0644);
MODULE_PARM_DESC(rx_trace, "number of received frames to log (0 = off)");
