// SPDX-License-Identifier: GPL-2.0
/*
 * Shadow layer, part 1 of 3: struct timer_list.
 *
 * The blob embeds 2.6.36 timer_lists inside its own allocations and drives them
 * through init_timer_key / add_timer / del_timer. Both the layout and the
 * callback contract changed:
 *
 *              2.6.36            6.12
 *   entry      0                 0        (list_head -> hlist_node, both 8B)
 *   expires    8                 8
 *   base       12                -
 *   function   16                12       <-- MOVED
 *   data       20                gone     <-- removed in 4.15
 *   slack      24                -
 *   sizeof     28                20
 *
 *   callback   void (*)(unsigned long data)   void (*)(struct timer_list *)
 *
 * So the blob writes its callback at +16 and its cookie at +20, while the
 * kernel reads a callback from +12. Left alone, every timer expiry jumps to
 * whatever sits at +16 in the blob's layout - which is `function` itself, i.e.
 * it calls the address of its own function pointer. That is a reliable crash
 * and the most likely cause of the insmod hang.
 *
 * Strategy: never let the kernel see the blob's timer at all. Keep a real
 * 6.12 timer_list of our own, hash-keyed on the blob's timer address, and
 * translate in a trampoline. The blob's struct is then pure private data that
 * only this file interprets.
 *
 * All three entry points are reached by objcopy --redefine-sym on the blob (see
 * the Makefile), NOT by defining the kernel's names. That leaves the genuine
 * add_timer/timer_setup/timer_delete available to this file, which is what
 * makes the translation possible at all.
 *
 * Offsets come from shadow/offsets-2.6.36.h, generated by `make offsets` -
 * not retyped by hand.
 */

#include <linux/kernel.h>
#include <linux/slab.h>
#include <linux/timer.h>
#include <linux/spinlock.h>
#include <linux/hashtable.h>

#include "shadow/offsets-2.6.36.h"
#include "wl_shadow.h"

/* The 2.6.36 callback signature: takes the cookie, not the timer. */
typedef void (*wl236_timer_fn)(unsigned long);

/* ---- accessors into the blob's 2.6.36-layout timer ------------------ */

static inline void **blob_entry_next(void *bt)
{
	return (void **)((u8 *)bt + WL236_TIMER_LIST_ENTRY);
}

static inline unsigned long blob_expires(void *bt)
{
	return *(unsigned long *)((u8 *)bt + WL236_TIMER_LIST_EXPIRES);
}

static inline wl236_timer_fn blob_function(void *bt)
{
	return *(wl236_timer_fn *)((u8 *)bt + WL236_TIMER_LIST_FUNCTION);
}

static inline unsigned long blob_data(void *bt)
{
	return *(unsigned long *)((u8 *)bt + WL236_TIMER_LIST_DATA);
}

/* ---- the side table ------------------------------------------------- */

struct wl_timer_map {
	struct hlist_node	link;
	void			*blob;	/* the blob's 28-byte timer_list */
	struct timer_list	real;	/* the one the kernel knows about */
};

static DEFINE_HASHTABLE(wl_timer_ht, 6);
static DEFINE_SPINLOCK(wl_timer_lock);

/* caller holds wl_timer_lock */
static struct wl_timer_map *map_find(void *blob)
{
	struct wl_timer_map *m;

	hash_for_each_possible(wl_timer_ht, m, link, (unsigned long)blob)
		if (m->blob == blob)
			return m;
	return NULL;
}

/*
 * 2.6.36's timer_pending() is a static inline the blob has compiled in as
 * (timer->entry.next != NULL). Nothing else maintains that field once the
 * kernel stops seeing this struct, so we have to. The value is arbitrary as
 * long as it is non-NULL; the map pointer is convenient and debuggable.
 */
static inline void blob_set_pending(struct wl_timer_map *m, bool pending)
{
	*blob_entry_next(m->blob) = pending ? m : NULL;
}

/* ---- trampoline ----------------------------------------------------- */

static void wl_timer_trampoline(struct timer_list *t)
{
	struct wl_timer_map *m = container_of(t, struct wl_timer_map, real);
	wl236_timer_fn fn;
	unsigned long data, flags;

	spin_lock_irqsave(&wl_timer_lock, flags);
	/* Clear pending BEFORE the callback: wl handlers routinely re-arm
	 * themselves, and would otherwise see a stale pending state. */
	blob_set_pending(m, false);
	fn = blob_function(m->blob);
	data = blob_data(m->blob);
	spin_unlock_irqrestore(&wl_timer_lock, flags);

	if (fn)
		fn(data);
	else
		pr_warn_once("wl: timer %p expired with a NULL callback\n", m->blob);
}

/* ---- the three rerouted entry points -------------------------------- */

/*
 * 2.6.36: void init_timer_key(struct timer_list *, const char *name,
 *                             struct lock_class_key *key)
 *
 * Note this is exactly the ABI drift the link experiment could not see:
 * init_timer_key still exists and is still exported in 6.12, so the blob's
 * call linked cleanly - straight into a five-argument function, passing `name`
 * where `func` was expected. Rerouting here is what stops that.
 */
void wl_shim_init_timer_key(void *blob_timer, const char *name, void *key)
{
	struct wl_timer_map *m, *dup;
	unsigned long flags;

	/* wl re-inits its timers across up/down cycles, so a repeat init on the
	 * same address is normal, not an error. Reuse the mapping. */
	spin_lock_irqsave(&wl_timer_lock, flags);
	dup = map_find(blob_timer);
	spin_unlock_irqrestore(&wl_timer_lock, flags);

	if (dup) {
		/* Outside the lock: this can sleep. */
		timer_delete_sync(&dup->real);
		spin_lock_irqsave(&wl_timer_lock, flags);
		blob_set_pending(dup, false);
		spin_unlock_irqrestore(&wl_timer_lock, flags);
		return;
	}

	/* GFP_ATOMIC: wl's attach path is not reliably sleepable. */
	m = kzalloc(sizeof(*m), GFP_ATOMIC);
	if (!m) {
		pr_err("wl: no memory for timer map (%p); this timer will not fire\n",
		       blob_timer);
		return;
	}

	m->blob = blob_timer;
	timer_setup(&m->real, wl_timer_trampoline, 0);

	spin_lock_irqsave(&wl_timer_lock, flags);
	blob_set_pending(m, false);
	hash_add(wl_timer_ht, &m->link, (unsigned long)blob_timer);
	spin_unlock_irqrestore(&wl_timer_lock, flags);
}

/* 2.6.36: void add_timer(struct timer_list *) - arms at timer->expires. */
void wl_shim_add_timer(void *blob_timer)
{
	struct wl_timer_map *m;
	unsigned long flags, expires;

	spin_lock_irqsave(&wl_timer_lock, flags);
	m = map_find(blob_timer);
	if (m) {
		expires = blob_expires(blob_timer);
		blob_set_pending(m, true);
	}
	spin_unlock_irqrestore(&wl_timer_lock, flags);

	if (!m) {
		pr_warn_once("wl: add_timer on unmapped timer %p (missed init?)\n",
			     blob_timer);
		return;
	}

	/* add_timer() BUGs on an already-pending timer. 2.6.36's did too, but do
	 * not rely on the blob being well-behaved across an ABI change. */
	if (timer_pending(&m->real))
		mod_timer(&m->real, expires);
	else {
		m->real.expires = expires;
		add_timer(&m->real);
	}
}

/*
 * 2.6.36: int del_timer(struct timer_list *) - returns 1 if it actually
 * dequeued a pending timer. Deliberately the async variant: the blob may call
 * this from atomic context, so timer_delete_sync() is not safe here.
 */
int wl_shim_del_timer(void *blob_timer)
{
	struct wl_timer_map *m;
	unsigned long flags;
	int was_pending = 0;

	spin_lock_irqsave(&wl_timer_lock, flags);
	m = map_find(blob_timer);
	if (m) {
		was_pending = (*blob_entry_next(blob_timer) != NULL);
		blob_set_pending(m, false);
	}
	spin_unlock_irqrestore(&wl_timer_lock, flags);

	if (!m)
		return 0;

	timer_delete(&m->real);
	return was_pending;
}

/* ---- lifecycle ------------------------------------------------------ */

void wl_shadow_timer_exit(void)
{
	struct wl_timer_map *m;
	struct hlist_node *tmp;
	unsigned long flags;
	int bkt, n = 0;

	/*
	 * 2.6.36 had no destroy_timer(), so nothing tells us when the blob is
	 * finished with one - entries live until unload. Reap them here.
	 */
	hash_for_each_safe(wl_timer_ht, bkt, tmp, m, link) {
		timer_delete_sync(&m->real);
		spin_lock_irqsave(&wl_timer_lock, flags);
		hash_del(&m->link);
		spin_unlock_irqrestore(&wl_timer_lock, flags);
		kfree(m);
		n++;
	}

	if (n)
		pr_info("wl: shadow timer table freed (%d entries)\n", n);
}
